name: Deploy and Restart Services

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > key_file.key
        chmod 600 key_file.key
        eval "$(ssh-agent -s)"
        ssh-add key_file.key

    - name: Execute Commands on Oracle Cloud Instance
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@168.138.94.153 << 'EOF'
        cd ensf-619-be/
        git pull origin main
        sudo systemctl daemon-reload
        sudo systemctl restart gunicorn
        sudo systemctl restart nginx
        EOF
